### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Binary-Compatibility-Enforcer-Plugin#2]
add something like the following

when using code like this 

```
 builder = new ProcessBuilder( "/bin/bash", "-c", "git " + cmd);
```

change it to something like:
```
     String osName = System.getProperty("os.name");
        if(osName != null && osName.contains("Windows")) {
            builder = new ProcessBuilder( "C:\\WINDOWS\\system32\\cmd.exe", "/C", "C:\\cygwin64\\bin\\git " + cmd);
        } else {
            builder = new ProcessBuilder( "/bin/bash", "-c", "git " + cmd);
        }
```

**Comment by tgd** [comment]
Closing this out as no work is planned on this at the moment. Please comment on this issue if you would like it re-opened. If you would like to expedite the development of this please get in touch with us here for commercial support: https://chronicle.software/contact-us/
